- name: Stop Apache Log Generator
  hosts: all
  strategy: free
  become: true
  become_method: sudo
  vars:
    INSTALL_DIR: "/opt/apache-log-generator"
    PID_FILE: "{{ INSTALL_DIR }}/generator.pid"
  tasks:
    - name: Stop Apache Log Generator
      shell: "kill $(cat {{ PID_FILE}})"
