---
- name: Delete Docker Container
  hosts: all
  become: true
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
  tasks:
  - name: delete docker container
    community.docker.docker_container: 
      name: "{{CONTAINER_ID}}"
      state: absent
