---
- name: setup docker env
  ansible.builtin.set_fact:
    DOCKER_ENV: "{{ENV_VARS}}"
  no_log: true
  when: ENV_VARS | length > 0

- name: setup docker exposed ports
  ansible.builtin.set_fact:
    DOCKER_EXP_PORTS: "{{EXPOSED_PORTS}}"
  when: EXPOSED_PORTS | length > 0

- name: setup docker published ports 
  ansible.builtin.set_fact:
    DOCKER_PUB_PORT: "{{PUBLISHED_PORTS}}"
  when: PUBLISHED_PORTS | length > 0

- name: setup docker volumes 
  ansible.builtin.set_fact:
    DOCKER_VOLUMES: "{{VOLUMES}}"
  when: VOLUMES | length > 0

- name: Docker container
  community.docker.docker_container: 
    name: "{{NODE}}-{{INSTANCE}}"
    auto_remove: "{{AUTO_REMOVE}}"
    cleanup: "{{CLEANUP}}"
    # cpus: "{{CPU_SHARE}}"
    detach: "{{DETACH}}"
    env: "{{DOCKER_ENV}}"
    exposed_ports: "{{DOCKER_EXP_PORTS}}"
    image: "{{IMAGE}}"
    keep_volumes: "{{KEEP_VOLUMES}}"
    memory: "{{MEM_SHARE_LIMIT}}"
    memory_reservation: "{{MEM_SHARE}}"
    published_ports: "{{DOCKER_PUB_PORT}}"
    restart_policy: "{{RESTART_POLICY}}"
    shm_size: "{{SHM_SIZE}}"
    user: "{{ USER }}"
    volumes: "{{ DOCKER_VOLUMES }}"
    state: "{{ DOCKER_STATE }}"
    working_dir: "{{ WORKDIR }}"
  register: docker_res
