---
- name: setup docker env
  ansible.builtin.set_fact:
    DOCKER_ENV: "{{ENV_VARS}}"
  no_log: true
  when: ENV_VARS | length > 0

- name: setup docker published ports 
  ansible.builtin.set_fact:
    DOCKER_PUB_PORT: "{{PUBLISHED_PORTS}}"
  when: PUBLISHED_PORTS | length > 0

- name: Docker container
  community.docker.docker_container: 
    name: "{{NODE}}-{{INSTANCE}}"
    env: "{{DOCKER_ENV}}"
    image: "{{IMAGE}}"
    published_ports: "{{DOCKER_PUB_PORT}}"
    restart_policy: "{{RESTART_POLICY}}"
    state: "{{ DOCKER_STATE }}"
  register: docker_res
