---
- name: Start Docker Container
  hosts: all
  become: true
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
    DOCKER_ENV: {}
    DOCKER_EXP_PORTS: []
    DOCKER_PUB_PORT: []
    DOCKER_VOLUMES: []
    DOCKER_STATE: "started"
  tasks:
  - import_tasks: docker_container_tasks.yaml
