#
# Ystia Forge
# Copyright (C) 2018 Bull S. A. S. - Bull, Rue Jean Jaures, B.P.68, 78340, Les Clayes-sous-Bois, France.
# Use of this source code is governed by Apache 2 LICENSE that can be found in the LICENSE file.
#


- name: Remove a Traefik route service
  hosts: all
  strategy: free
  become: true
  tasks:

    - name: Remove route from traefik config file
      blockinfile:
        marker: "# {mark} ANSIBLE MANAGED BLOCK {{TARGET_INSTANCE}}"
        dest: "{{CONFIG_DIR}}/traefik.d/{{SOURCE_NODE}}-route.toml"
        state: absent

