---
- name: Configure docker proxy
  hosts: all
  become: true
  strategy: linear
  
  tasks:
    - name: create docker.service.d directory
      ansible.builtin.file:
        path: /etc/systemd/system/docker.service.d
        state: directory

    - name: Generate http-proxy.conf file
      ansible.builtin.template:
        src: "http-proxy.conf.j2"
        dest: /etc/systemd/system/docker.service.d/http-proxy.conf
