
---
- name: Start Docker
  hosts: all
  become: true

  tasks:
    - name: Enable docker service
      ansible.builtin.service: 
        name: docker
        daemon_reload: true
        state: restarted
