#
# Ystia Forge
# Copyright (C) 2018 Bull S. A. S. - Bull, Rue Jean Jaures, B.P.68, 78340, Les Clayes-sous-Bois, France.
# Use of this source code is governed by Apache 2 LICENSE that can be found in the LICENSE file.
#

- import_playbook: ../commons/docker/create.yaml

- import_playbook: ../commons/kubeadm/create.yaml

- name: Generate certificates
  hosts: all
  strategy: linear
  become: true
  tasks:
    - name: Download cfssl
      get_url:
        url: "{{CFSSL_DOWNLOAD_URL}}/cfssl_linux-amd64"
        dest: /usr/local/bin/cfssl
        mode: 0755

    - name: Download cfssljson
      get_url:
        url: "{{CFSSL_DOWNLOAD_URL}}/cfssljson_linux-amd64"
        dest: /usr/local/bin/cfssljson
        mode: 0755

    - name: Create pki directories
      file:
        path: "/etc/kubernetes/pki/etcd"
        state: directory
        owner: root
        group: root
        mode: "u=rwx,g=rx,o=rx"

    - name: Copy ca-config
      copy:
        src: "files/ca-config.json"
        dest: "/etc/kubernetes/pki/ca-config.json"
      when: inventory_hostname == ansible_play_hosts[0]

    - name: Copy CA certificate
      copy:
        content: "{{CA_CERT}}"
        dest: "/etc/kubernetes/pki/ca.crt"
      when:
        - CA_CERT != ""
        - CA_KEY != ""
        - inventory_hostname == ansible_play_hosts[0]

    - name: Copy CA key
      copy:
        content: "{{CA_KEY}}"
        dest: "/etc/kubernetes/pki/ca.key"
      when:
        - CA_CERT != ""
        - CA_KEY != ""
        - inventory_hostname == ansible_play_hosts[0]
