#
# Ystia Forge
# Copyright (C) 2018 Bull S. A. S. - Bull, Rue Jean Jaures, B.P.68, 78340, Les Clayes-sous-Bois, France.
# Use of this source code is governed by Apache 2 LICENSE that can be found in the LICENSE file.
#

- import_playbook: ../commons/kubeadm/start.yaml

- name: Start Kubernetes master
  hosts: all
  strategy: linear
  become: true
  tasks:
    - name: log wait for start
      debug: msg="Waiting until Kubernetes node became Ready"

    - name: Wait for start
      shell:
        source /etc/profile;
        kubectl get --no-headers nodes "{{ansible_hostname}}" | awk '{print $2}'
      register: result
      until: result.stdout == "Ready"
      retries: 300
      delay: 10
