#
# Ystia Forge
# Copyright (C) 2018 Bull S. A. S. - Bull, Rue Jean Jaures, B.P.68, 78340, Les Clayes-sous-Bois, France.
# Use of this source code is governed by Apache 2 LICENSE that can be found in the LICENSE file.
#


- name: Configure resolv.conf
  hosts: all
  become: true
  tasks:
    - name: Configure DNS servers
      template:
        src: resolv.conf.j2
        dest: "/etc/resolv.conf"
        mode: 0644

    - name: Get hostname
      shell: hostname -s
      register: hostname_result

    - name: Set hostname fact
      set_fact:
        HOSTNAME: "{{hostname_result.stdout_lines[0]}}"
