#
# Ystia Forge
# Copyright (C) 2018 Bull S. A. S. - Bull, Rue Jean Jaures, B.P.68, 78340, Les Clayes-sous-Bois, France.
# Use of this source code is governed by Apache 2 LICENSE that can be found in the LICENSE file.
#

- name: "Remove instance from resolv.conf"
  hosts: all
  become: true
  tasks:
    - name: "Remove {{TARGET_INSTANCE}} from resolv.conf"
      blockinfile:
        path: "/etc/resolv.conf"
        state: absent
        marker: "# {mark} ANSIBLE MANAGED BLOCK {{TARGET_INSTANCE}}"
        block: |
              nameserver {{IP_ADDRESS}}
