---
- name: prepare yorc host
  hosts: yorc

  vars:
    consul_version: 1.10.0
    terraform_version: 1.0.2

  pre_tasks:
    - name: install required packages
      become: true
      ansible.builtin.apt:
        update_cache: true
        name:
          - docker.io

    - name: add ansible user to docker group
      become: true
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true

    - name: copy docker-compose directory
      ansible.posix.synchronize:
        src: "../docker-compose"
        dest: "~/."
