#
# ================================== Elasticsearch Configuration ===================================
#
# The backup of the original Elasticsearch configuration file is 'elasticsearch.yml.original_backup'
#
# This is below, the specific configuration for the Ystia Forge Elasticsearch component
#

#cluster.name: my-application
#node.name: node-1
#discovery.zen.ping.unicast.hosts: ["host1", "host2"]
network.bind_host: 0.0.0.0
#network.publish_host: x.x.x.x
