---

- name: Set SLURM common variables (Debian)
  set_fact:
    slurm_user_uid: 567
    slurm_user_gid: 567
    slurm_etc_dir: /etc/slurm
    slurm_log_dir: /var/log/slurm
    slurm_pid_dir: /var/run
    slurm_spool_dir: /var/spool/slurmd

- name: Install ruby/gem and required tools to build Slurm packages (Debian)
  package: name={{ item }}
  with_items:
    - ruby
    - ruby-dev
    - gcc
    - make
    - libpam0g-dev
    - munge
    - libmunge-dev
    - libmunge2

- name: Install fpm with gem (Debian)
  gem:
    name: fpm
    user_install: no

- name: Download Slurm archive
  get_url:
    url: "{{ DOWNLOAD_URL }}"
    dest: /tmp/
    mode: 0440
  register: dl_archive

- name: Extract Slurm archive
  unarchive:
    src: "{{ dl_archive.dest }}"
    dest: /tmp/slurm
    extra_opts: ["--strip-components", "1"]
    remote_src: yes

- name: Configure Slurm build options
  shell: "./configure --prefix=/usr --sysconfdir={{slurm_etc_dir}}"
  args:
    chdir: "/tmp/slurm"

- name: Warn about build duration
  debug:
    msg: "Now building Slurm packages from sources. This can take a while."

- name: Build Slurm (make default)
  make:
    chdir: "/tmp/slurm"

- name: Build Slurm (make install DESTDIR=/tmp/slurm-build)
  make:
    chdir: "/tmp/slurm"
    target: install
    params:
      DESTDIR: "/tmp/slurm-build"

- name: Build Slurm Debian package in order to install it
  shell: "fpm -s dir -t deb -v 1.0 -n slurm -C /tmp/slurm-build --force ."
  args:
    chdir: /tmp

- name: Install Slurm Debian package
  apt:
    deb: "/tmp/slurm_1.0_amd64.deb"

- name: Install systemd slurmctld service
  copy:
    src: slurmctld.service
    dest: /lib/systemd/system/slurmctld.service

- name: Install systemd slurmd service
  copy:
    src: slurmd.service
    dest: /lib/systemd/system/slurmd.service

- name: Reload systemd configuration
  systemd:
    daemon_reload: yes

- name: Remove Slurm installation artifacts
  file:
    path: "{{item}}"
    state: absent
  with_items:
    - "/tmp/slurm"
    - "{{ dl_archive.dest }}"
    - "/tmp/slurm_1.0_amd64.deb"
    - /tmp/slurm-build
