#
# Ystia Forge
# Copyright (C) 2018 Bull S. A. S. - Bull, Rue Jean Jaures, B.P.68, 78340, Les Clayes-sous-Bois, France.
# Use of this source code is governed by Apache 2 LICENSE that can be found in the LICENSE file.
#

- name: "Add instance to ntp.conf"
  hosts: all
  become: true
  tasks:
    - name: "Add {{TARGET_INSTANCE}} to ntp.conf"
      blockinfile:
        path: "/etc/ntp.conf"
        state: absent
        marker: "# {mark} ANSIBLE MANAGED BLOCK {{TARGET_INSTANCE}}"
        block: |
          server {{IP_ADDRESS}} iburst 

    - name: Set NTP variables (RedHat)
      set_fact:
        ntp_service: "ntpd"
      when: ansible_os_family == 'RedHat'

    - name: Set NTP variables (Debian)
      set_fact:
        ntp_service: "ntp"
      when: ansible_os_family == 'Debian'

    - name: Restarting NTP service
      service:
        name: "{{ ntp_service }}"
        enabled: yes
        state: restarted